---
aad-pod-identity:
  azureIdentities:
%{for k, v in azureidentities~}
    ${k}:
      namespace: "${v.namespace}"
      name: "${v.name}"
      type: 0
      resourceID: "${v.resource_id}"
      clientID: "${v.client_id}"
      binding:
        name: "${v.name}"
        selector: "${v.name}"
%{endfor~}